const logoCss=document.createElement('link');logoCss.rel='stylesheet';logoCss.href='logo.css?v=20260919';document.head.appendChild(logoCss);
const menuBtn=document.querySelector('.menu-btn');const mobileNav=document.querySelector('.mobile-nav');if(menuBtn&&mobileNav){menuBtn.addEventListener('click',()=>mobileNav.classList.toggle('open'));mobileNav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>mobileNav.classList.remove('open')))}
const cookie=document.querySelector('.cookie');if(cookie&&localStorage.getItem('hey-cookie-choice'))cookie.style.display='none';document.querySelectorAll('[data-cookie]').forEach(button=>button.addEventListener('click',()=>{localStorage.setItem('hey-cookie-choice',button.dataset.cookie);if(cookie)cookie.style.display='none'}));
const track=document.querySelector('.projects-track');const dots=[...document.querySelectorAll('.dot')];let slideIndex=0;let autoSlide;
function getSlideStep(){const card=track?.querySelector('.project-card');return card?card.getBoundingClientRect().width+16:0}
function updateDots(){dots.forEach((dot,index)=>dot.classList.toggle('active',index===Math.min(slideIndex,dots.length-1)))}
function syncSlideIndex(){const step=getSlideStep();if(!track||!step)return;slideIndex=Math.round(track.scrollLeft/step);updateDots()}
function move(direction=1){if(!track)return;const step=getSlideStep();if(!step)return;const visible=innerWidth<=860?1:3;const max=Math.max(0,track.children.length-visible);slideIndex=Math.max(0,Math.min(max,slideIndex+direction));track.scrollTo({left:step*slideIndex,behavior:'smooth'});updateDots()}
function stopAutoSlide(){if(autoSlide)clearInterval(autoSlide)}
document.querySelector('.slider-btn.next')?.addEventListener('click',()=>move(1));document.querySelector('.slider-btn.prev')?.addEventListener('click',()=>move(-1));
if(track){let scrollTimer;track.addEventListener('scroll',()=>{clearTimeout(scrollTimer);scrollTimer=setTimeout(syncSlideIndex,80)},{passive:true});track.addEventListener('pointerdown',stopAutoSlide,{passive:true});track.addEventListener('touchstart',stopAutoSlide,{passive:true});autoSlide=setInterval(()=>{const visible=innerWidth<=860?1:3;const max=Math.max(0,track.children.length-visible);if(max<1)return;if(slideIndex>=max)slideIndex=-1;move(1)},4500)}
const form=document.querySelector('#contact-form');if(form){form.addEventListener('submit',event=>{event.preventDefault();const notice=document.querySelector('.notice');if(notice){notice.style.display='block';notice.textContent='Formularen sender ikke endnu. Skriv direkte til info@heymontage.dk.'}})}
